---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
platforms:
- name: ubuntu-14.04
  driver_config:
    box: cloud-ubuntu1204
    box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[chef_delivery::default]
    attributes: