name             'chef_delivery'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef_delivery'
long_description 'Installs/Configures chef_delivery'
version          '0.1.0'
